export const CAMPUS_EVENTS = [
  {
    id: '1',
    title: 'Cycle Rush - OwlFit Group Fitness',
    category: 'Sports',
    date: 'Mar 27, 2026',
    time: '9:00 AM',
    location: 'Recreation Center',
    campus: 'kennesaw',
    type: 'sports',
    coordinate: { latitude: 34.0385, longitude: -84.5820 },
    image: 'https://picsum.photos/seed/cycle/80/80',
  },
  {
    id: '2',
    title: 'The Write Place: Creative Writing Club',
    category: 'Workshop',
    date: 'Mar 27, 2026',
    time: '2:00 PM',
    location: 'English Building 101',
    campus: 'kennesaw',
    type: 'music',
    coordinate: { latitude: 34.0400, longitude: -84.5805 },
    image: 'https://picsum.photos/seed/write/80/80',
  },
  {
    id: '3',
    title: '3D Lab - Check In',
    category: 'Workshop',
    date: 'Mar 28, 2026',
    time: '10:00 AM',
    location: '3D Lab, STEM Building',
    campus: 'kennesaw',
    type: 'mental_health',
    coordinate: { latitude: 34.0375, longitude: -84.5825 },
    image: 'https://picsum.photos/seed/lab/80/80',
  },
  {
    id: '4',
    title: 'Miracle at KSU Board Meeting',
    category: 'Campus',
    date: 'Mar 28, 2026',
    time: '3:00 PM',
    location: 'Student Center Room 302',
    campus: 'kennesaw',
    type: 'mental_health',
    coordinate: { latitude: 34.0395, longitude: -84.5815 },
    image: 'https://picsum.photos/seed/ksu/80/80',
  },
  {
    id: '5',
    title: 'Marietta Wellness Walk',
    category: 'Sports',
    date: 'Mar 29, 2026',
    time: '8:00 AM',
    location: 'Marietta Campus Lawn',
    campus: 'marietta',
    type: 'sports',
    coordinate: { latitude: 33.9370, longitude: -84.5210 },
    image: 'https://picsum.photos/seed/walk/80/80',
  },
  {
    id: '6',
    title: 'Mental Health Awareness Talk',
    category: 'Mental Health',
    date: 'Mar 30, 2026',
    time: '1:00 PM',
    location: 'Marietta Student Lounge',
    campus: 'marietta',
    type: 'mental_health',
    coordinate: { latitude: 33.9410, longitude: -84.5160 },
    image: 'https://picsum.photos/seed/mental/80/80',
  },
];

export const CAMPUSES = [
  {
    id: 'kennesaw',
    label: 'Kennesaw Campus',
    region: {
      latitude: 34.0389,
      longitude: -84.5816,
      latitudeDelta: 0.008,
      longitudeDelta: 0.008,
    },
  },
  {
    id: 'marietta',
    label: 'Marietta Campus',
    region: {
      latitude: 33.9385,
      longitude: -84.5187,
      latitudeDelta: 0.025,
      longitudeDelta: 0.025,
    },
  },
];