export const CAMPUS_EVENTS = [
  {
    id: '1',
    title: 'Cycle Rush - OwlFit Group Fitness',
    category: 'Wellness',
    date: 'Mar 27, 2026',
    time: '9:00 AM',
    location: 'Recreation Center',
    type: 'counseling',
    image: 'https://picsum.photos/seed/cycle/80/80',
  },
  {
    id: '2',
    title: 'The Write Place: Creative Writing Club',
    category: 'Workshop',
    date: 'Mar 27, 2026',
    time: '2:00 PM',
    location: 'English Building 101',
    type: 'workshop',
    image: 'https://picsum.photos/seed/write/80/80',
  },
  {
    id: '3',
    title: '3D Lab - Check In',
    category: 'Workshop',
    date: 'Mar 28, 2026',
    time: '10:00 AM',
    location: '3D Lab, STEM Building',
    type: 'workshop',
    image: 'https://picsum.photos/seed/lab/80/80',
  },
  {
    id: '4',
    title: 'Miracle at KSU Board Meeting',
    category: 'Campus',
    date: 'Mar 28, 2026',
    time: '3:00 PM',
    location: 'Student Center Room 302',
    type: 'counseling',
    image: 'https://picsum.photos/seed/ksu/80/80',
  },
];